# Generated by Django 3.2.7 on 2023-06-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0007_alter_channel_channel_art'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communitycomment',
            options={'verbose_name': 'Community Comment', 'verbose_name_plural': 'Community Comments'},
        ),
        migrations.AlterField(
            model_name='channel',
            name='instagram',
            field=models.URLField(default='https://instagram.com/'),
        ),
    ]
